services:
  - type: web
    name: rezoomex-mcp-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REZOOMEX_BASE_URL
        value: https://awsapi-gateway.rezoomex.com
      - key: REZOOMEX_LOGIN_URL
        value: https://workspace.rezoomex.com/account/login
      - key: LOG_LEVEL
        value: info
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: CORS_ORIGIN
        value: "*"
